package:
  name: python.app
  version: 1.2

build:
  number: 1000
  skip: True  # [not osx]

requirements:
  host:
    - python
  run:
    - python

test:
  files:
    - t.py
  commands:
    - python.app -V
    - pythonw -V

about:
  home: https://www.python.org/
  license: BSD
  summary: Proxy on OS X letting Python libraries hook into the gui event loop

extra:
  recipe-maintainers:
    - cpbotha
    - ChrisBarker-NOAA
