package:
  name: python.app
  version: 1.2

build:
  number: 1204
  skip: True  # [not osx]

requirements:
  build:
    # add this to force gcc7 builds
    - {{ compiler('c') }}
  host:
    - python
  run:
    - python

test:
  files:
    - t.py
    - test_versions.sh
  commands:
    - python.app -V
    - pythonw -V
    - bash test_versions.sh

about:
  home: https://www.python.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Proxy on OS X letting Python libraries hook into the gui event loop

extra:
  recipe-maintainers:
    - cpbotha
    - ChrisBarker-NOAA
    - hoechenberger
